{
  "formatVersion": "1.1",
  "component": {
    "group": "com.axb.plugin",
    "module": "noDoubleClickPlugin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "l3mnlfnhljf6hcmgbjlkemgxom"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "noDoubleClickPlugin-0.0.1.jar",
          "url": "noDoubleClickPlugin-0.0.1.jar",
          "size": 15933,
          "sha512": "45172a3a0dcd422b19026bf02d333b30aa318477914b2be340a5bc94b7f70fe4ded9cddbe4b90da52c79f65e6cf46b7e9bdd30a3d18e298aa79cfca04f39ab57",
          "sha256": "9320e9fb3e93c790efc6c62d0e7984232cbd2680ba8e849461a0958522600c18",
          "sha1": "5313b084c77000c3c8d36a1b43f9d6bd96f374e3",
          "md5": "54e306dd1b316e57f7fb2ac34e17b54e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "noDoubleClickPlugin-0.0.1.jar",
          "url": "noDoubleClickPlugin-0.0.1.jar",
          "size": 15933,
          "sha512": "45172a3a0dcd422b19026bf02d333b30aa318477914b2be340a5bc94b7f70fe4ded9cddbe4b90da52c79f65e6cf46b7e9bdd30a3d18e298aa79cfca04f39ab57",
          "sha256": "9320e9fb3e93c790efc6c62d0e7984232cbd2680ba8e849461a0958522600c18",
          "sha1": "5313b084c77000c3c8d36a1b43f9d6bd96f374e3",
          "md5": "54e306dd1b316e57f7fb2ac34e17b54e"
        }
      ]
    }
  ]
}
